# Generated by Django 4.1.2 on 2023-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_conf_name', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=500)),
                ('Start_date', models.IntegerField()),
                ('End_date', models.IntegerField()),
                ('calendar', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='individual_pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pub', models.IntegerField()),
                ('pub_THname', models.CharField(max_length=500)),
                ('pub_ENGname', models.CharField(max_length=500)),
                ('journal_DB', models.CharField(max_length=255)),
                ('journal_conf_name', models.CharField(max_length=500)),
                ('Imple_organ', models.CharField(max_length=500)),
                ('release_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='progress_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_Master', models.IntegerField()),
                ('Master_no', models.CharField(max_length=50)),
                ('Master_course', models.CharField(max_length=50)),
                ('Master_name', models.CharField(max_length=255)),
                ('study_plan', models.CharField(max_length=50)),
                ('stu_status', models.CharField(max_length=100)),
                ('graduation_y', models.DateField()),
                ('pub_THname', models.CharField(max_length=500)),
                ('Advisor_1', models.CharField(max_length=255)),
                ('Advisor_2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='progress_phd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_PhD', models.IntegerField()),
                ('PhD_no', models.CharField(max_length=50)),
                ('PhD_course', models.CharField(max_length=50)),
                ('PhD_name', models.CharField(max_length=255)),
                ('study_plan', models.CharField(max_length=50)),
                ('stu_status', models.CharField(max_length=100)),
                ('graduation_y', models.DateField()),
                ('pub_THname', models.CharField(max_length=500)),
                ('Advisor_1', models.CharField(max_length=255)),
                ('Advisor_2', models.CharField(max_length=255)),
            ],
        ),
    ]
