# Generated by Django 4.1.2 on 2023-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='End_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='calendar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress_master',
            name='graduation_y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress_phd',
            name='graduation_y',
            field=models.IntegerField(),
        ),
    ]
