# Generated by Django 4.1.2 on 2023-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSData', '0002_alter_conference_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='calendar',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progress_master',
            name='graduation_y',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progress_phd',
            name='graduation_y',
            field=models.DateField(),
        ),
    ]
