# Generated by Django 4.1.2 on 2023-03-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMSData', '0004_alter_conference_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='calendar',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='progress_master',
            name='graduation_y',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='progress_phd',
            name='graduation_y',
            field=models.CharField(max_length=4),
        ),
    ]
